version: 2
jobs:
  sca:
     machine:
      image: ubuntu-1604:201903-01
     steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install cppcheck'
      - run: 'cppcheck *.* --language=c++ --enable=warning --error-exitcode=1'
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'
  doxygen:
     docker:
      - image: vasaszs/doxygen:doxygen-image
     steps:
      - checkout
      - run: 'cd Doxygen && doxygen && make -C latex/.'
      - store_artifacts:
          path: Doxygen/latex/refman.pdf
          destination: documentation.pdf

workflows:
  version: 2
  sca_build_and_test:
    jobs:  
      - sca
      - build
      - test:
          requires:
            - build
      - doxygen 