version: 2
jobs:
  sca:
     machine:
      image: ubuntu-1604:201903-01
     steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install cppcheck'
      - run: 'cppcheck *.* --language=c++ --enable=warning --error-exitcode=1'
  build:
    docker:
      - image: vasaszs/gtest:gtest2
    steps:
      - checkout
      - run: 
          name: 'Unit testing'
          command: |
            git submodule init
            git submodule update
            cd /usr/src/gtest
            cmake CMakeLists.txt
            make
            cp *.a /usr/lib
            cd $HOME/project
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - ./test.o
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'
  unittest:
    docker:
      - image: vasaszs/gtest:gtest2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: 'Build Unit Test'
          command: 'make test'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
workflows:
  version: 2
  sca_build_and_test:
    jobs:
      - sca
      - build
      - test:
          requires:
            - build
      - unittest:
          requires:
            - build
