version: 2
jobs:
  sca:
     machine:
      image: ubuntu-1604:201903-01
     steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install cppcheck'
      - run: 'cppcheck *.* --language=c++ --enable=warning --error-exitcode=1'
  build:
    docker:
      - image: vasaszs/ubuntu16_image:ubuntubuild1604image
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    docker:
      - image: vasaszs/ubuntu16_image:ubuntubuild1604image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'

workflows:
  version: 2
  sca_build_and_test:
    jobs:
      - sca
      - build
      - test:
          requires:
            - build
