version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
	name: script
	command: |
             chmod 755 test
             ./test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
